service: sls-boilerplate

provider:
  name: aws
  tracing:
    apiGateway: true
    lambda: true
  runtime: nodejs10.x
  environment:
    TYPEORM_HOST: localhost
    TYPEORM_DATABASE: sls-boilerplate
    TYPEORM_PORT: 5432
    TYPEORM_SYNCHRONIZE: true
    TYPEORM_LOGGING: true
    TYPEORM_ENTITIES: api/data/entities/*.js

plugins:
  - serverless-plugin-monorepo
  - serverless-plugin-typescript
  - serverless-offline

functions:
  graphql:
    handler: api/lambdas/graphql.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
